### ISSUE TITLE
pldoc tree rollover makes tree wider

### ISSUE THREAD

**Issue by Anniepoo** [Anniepoo/swiplsitedesign#28]
rolling over the navigation tree on the website pldoc pages makes the three stop being overflow hidden and the whole tree gets wider.

**Comment by Anniepoo** [comment]
Fixed - pldoc.css to Jan

**Comment by JanWielemaker** [comment]
I'm not very happy with this.  As you've seen, this was deliberately done.  Quite a few section headers and
predicate names are too long for the navigation tree.  Making this tree (much) wider seems undesirable, but
being able to see the whole tree is necessary for navigation.

My original idea was to make the tree display over the contents when `hovered', but I failed to get that
working.  I'm happy with something better, but not with simply hiding the overflow.  A scroll-bar seems
bad too because it forces you to go down and never see the whole title or long predicate name.

**Comment by Anniepoo** [comment]
OK, maybe this is a good one for Jessica. I see your point. Visually, the elegant thing to do would be to have a violator - make just that line become visible. I'm just not sure how to accomplish that with CSS.
